spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    rest:
      basePath: /papyrus/core/api
  datasource:
    url: jdbc:h2:mem:operation-db
    driver-class-name: org.h2.Driver
    username: application-user
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:init-schema.sql
      mode: always
      data-locations: classpath:init-data.sql
      platform: h2

server:
  port: 8585
  servlet:
    context-path: /papyrus/core/api